site_name: pg_curl_worker
site_url: https://supabase.github.io/pg_curl_worker
site_description: A PostgreSQL extension for async networking

repo_name: supabase/pg_curl_worker
repo_url: https://github.com/supabase/pg_curl_worker

nav:
    - Welcome: 'index.md'
    - Installation: 'installation.md'
    - API Reference: 'api.md'
    - Contributing: 'contributing.md'
    - Roadmap: 'roadmap.md'


theme:
    name: 'material'
    favicon: 'assets/favicon.ico'
    logo: 'assets/favicon.ico'
    homepage: https://supabase.github.io/pg_curl_worker
    palette:
        primary: black
        accent: light green

markdown_extensions:
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - pymdownx.snippets
