name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Run make tests
      run: nix-shell --run "net-with-pg-13 make installcheck && net-with-pg-13 make installcheck"

    - name: Run pytest tests
      run: nix-shell --run "net-with-pg-13 python -m pytest"
