name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: set up python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: install pytest deps
      run: python -m pip install pytest psycopg2-binary sqlalchemy

    - name: Run make tests
      run: nix-shell --run "net-with-pg-13 make installcheck && net-with-pg-13 make installcheck"

    - name: Run pytest tests
      run: nix-shell --run "net-with-pg-13 python -m pytest"
